[package]
name = "renderer"
version = "0.1.0"
authors = ["Lóránt Meszlényi <meszlenyilorant@gmail.com>"]
edition = "2018"

[dependencies]
kiss3d = "0.18.0"
nalgebra = "0.17.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
